-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 11:45:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `height` INT NULL,
  `weight` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Foods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Foods` (
  `idFoods` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `calories` INT NOT NULL,
  `protein` INT NOT NULL,
  `carbs` INT NOT NULL,
  `fats` INT NOT NULL,
  PRIMARY KEY (`idFoods`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workouts` (
  `idWorkouts` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `calories_per_hour` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`idWorkouts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calorie_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calorie_log` (
  `idCalorie_log` INT NOT NULL,
  `Users_id` INT NOT NULL,
  `Foods_idFoods` INT NOT NULL,
  `calorie_intake` INT NULL,
  `date_of_log` DATE NULL,
  PRIMARY KEY (`idCalorie_log`, `Users_id`, `Foods_idFoods`),
  INDEX `fk_Calorie_log_Users_idx` (`Users_id` ASC) VISIBLE,
  INDEX `fk_Calorie_log_Foods1_idx` (`Foods_idFoods` ASC) VISIBLE,
  CONSTRAINT `fk_Calorie_log_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calorie_log_Foods1`
    FOREIGN KEY (`Foods_idFoods`)
    REFERENCES `mydb`.`Foods` (`idFoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workout_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workout_log` (
  `idWorkout_log` INT NOT NULL,
  `Users_id` INT NOT NULL,
  `Workouts_id` INT NOT NULL,
  `date_of_workout` DATE NULL,
  PRIMARY KEY (`idWorkout_log`, `Users_id`, `Workouts_id`),
  INDEX `fk_Workout_log_Users1_idx` (`Users_id` ASC) VISIBLE,
  INDEX `fk_Workout_log_Workouts1_idx` (`Workouts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Workout_log_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Workout_log_Workouts1`
    FOREIGN KEY (`Workouts_id`)
    REFERENCES `mydb`.`Workouts` (`idWorkouts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
